#!/bin/sh
set -e

echo "Running post-installation script...">/tmp/postinst.log
# Add any setup commands here, e.g., setting permissions or restarting services
pip install textual==1.0.0
pip install rapidfuzz==3.12.1
exit 0